---
- hosts: all
  remote_user: lakinduakash
  become: yes
  tasks:
  - name: ensure apache installed
    apt:
           name: apache2
           state: latest
    become_user: root
  - name: ensure apache is running
    service:
            name: apache2
            state: started 
