---
- hosts: all
  remote_user: lakinduakash
  become: yes
  tasks:
  - name: ensure apache installed
    apt:
           name: apache2
           state: latest
  - name: ensure git installed
    apt:
            name: git
            state: latest
  - name: ensure apache is running
    service:
            name: apache2
            state: started 
  - name: clone repo
    command: git clone https://github.com/lakinduakash/ansible-t1
    ignore_errors: True
  - name: fetch updates
    shell: chdir=/home/lakinduakash/ansible-t1 git pull origin master  
  - name: copy index.html
    command: cp -fp ansible-t1/index.html /var/www/html/index.html
    notify:
            - restart apache
  handlers:
            - name: restart apache
              service:
                      name: apache22
                      state: restarted
